server:
  port: 8081
  servlet:
    context-path: /
      #encoding:
      #charset: UTF-8
      #enabled: true
    #force: true

spring:
  data:
    redis:
      host: 127.0.0.1 #localhost
      port: 6379
      repositories: # Repository안쓰고, template 쓸꺼임
        enabled: false
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3307/ski_resort?serverTimezone=Asia/Seoul
    username: root
    password: "1234"

    #driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/fbase?serverTimezone=Asia/Seoul
    #username: root
    #password: "0000"
  output:
    ansi:
      enabled: always

  jpa:
    database: mysql # ????? ??
    open-in-view: true
    hibernate:
      ddl-auto: update #update,none,create(???????,???????, ??? ???? create ? ??? update? ????)
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      #use-new-id-generator-mappings: false # false-> jpa? ???? ?? ??? ?? ??, true? ? ??
    show-sql: true # Console??  Entity ??? ????. hibernate.format_sql: false
    properties:
      hibernate:
        format_sql: true


  jackson:
    serialization:
      fail-on-empty-beans: false
